### ISSUE TITLE
Plugin failed to load in RC v1.3.9

### ISSUE THREAD

**Issue by sai-mike** [jfcherng/roundcube-show-folder-size-plugin#2]
I just installed your v0.2.5 plugin and it is failing to load:

[19-Jun-2019 15:24:52 -0700]: PHP Error: Failed to load plugin file /var/www/roundcube/plugins/roundcube_show_folder_size_plugin/roundcube_show_folder_size_plugin.php in /var/www/roundcube/program/lib/Roundcube/rcube_plugin_api.php on line 173 (GET /roundcube/?_task=settings&_action=about)

Can this be fixed?

**Comment by jfcherng** [comment]
![image](https://user-images.githubusercontent.com/6594915/59807413-55dd8080-932a-11e9-81a5-19ca05e7510f.png)

Line 173 implies that PHP doesn't have the permission to read `plugins\show_folder_size\show_folder_size.php`.

---

![image](https://user-images.githubusercontent.com/6594915/59807472-9e953980-932a-11e9-8b72-0abf42b48dcc.png)

Test with RC 1.3.9 + PHP 7.3 = Working.

**Comment by sai-mike** [comment]
I used Composer to install the plugin.  

If you look at the error above, Composer created the plugin directory as /var/www/roundcube/plugins/roundcube_show_folder_size_plugin/ instead of /var/www/roundcube/plugins/show_folder_size/.  

Composer also adds the name of the plugin to /roundcube/config/config.inc.php as 'roundcube_show_folder_size_plugin' instead of 'show_folder_size'.

I renamed the plugin directory and edited RC's config.inc.php and now it loads.  It also looks like Composer is installing the dev-master instead of v0.2.5
![Selection_001](https://user-images.githubusercontent.com/35618397/59808602-d57b3900-92b1-11e9-9d88-68e7285cd5e2.png)

**Comment by jfcherng** [comment]
Thanks for providing useful information. Installation via composer should has been fixed now. 

You may have to manually edit the package name in `composer.json` if you have installed before.
`"jfcherng/roundcube-show-folder-size-plugin": "^0.2.5"` -> `"jfcherng/show-folder-size": "^0.2.5"`.
